/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.ocrstudio.sdk;

import ai.ocrstudio.sdk.*;

public class OCRStudioSDKException {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OCRStudioSDKException(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OCRStudioSDKException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(OCRStudioSDKException obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniocrstudiosdkJNI.delete_OCRStudioSDKException(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OCRStudioSDKException(String type, String msg) {
    this(jniocrstudiosdkJNI.new_OCRStudioSDKException__SWIG_0(type, msg), true);
  }

  public OCRStudioSDKException(OCRStudioSDKException copy) {
    this(jniocrstudiosdkJNI.new_OCRStudioSDKException__SWIG_1(OCRStudioSDKException.getCPtr(copy), copy), true);
  }

  public String Type() {
    return jniocrstudiosdkJNI.OCRStudioSDKException_Type(swigCPtr, this);
  }

  public String Message() {
    return jniocrstudiosdkJNI.OCRStudioSDKException_Message(swigCPtr, this);
  }

}
