/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.ocrstudio.sdk;

import ai.ocrstudio.sdk.*;

public class OCRStudioSDKString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OCRStudioSDKString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OCRStudioSDKString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(OCRStudioSDKString obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniocrstudiosdkJNI.delete_OCRStudioSDKString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OCRStudioSDKString() {
    this(jniocrstudiosdkJNI.new_OCRStudioSDKString__SWIG_0(), true);
  }

  public OCRStudioSDKString(String c_str) {
    this(jniocrstudiosdkJNI.new_OCRStudioSDKString__SWIG_1(c_str), true);
  }

  public OCRStudioSDKString(OCRStudioSDKString copy) {
    this(jniocrstudiosdkJNI.new_OCRStudioSDKString__SWIG_2(OCRStudioSDKString.getCPtr(copy), copy), true);
  }

  public String CStr() {
    return jniocrstudiosdkJNI.OCRStudioSDKString_CStr(swigCPtr, this);
  }

  public int Size() {
    return jniocrstudiosdkJNI.OCRStudioSDKString_Size(swigCPtr, this);
  }

}
