/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.ocrstudio.sdk;

import ai.ocrstudio.sdk.*;

public class OCRStudioSDKSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OCRStudioSDKSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OCRStudioSDKSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(OCRStudioSDKSession obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniocrstudiosdkJNI.delete_OCRStudioSDKSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String Description() {
    return jniocrstudiosdkJNI.OCRStudioSDKSession_Description(swigCPtr, this);
  }

  public void ProcessImage(OCRStudioSDKImage image) {
    jniocrstudiosdkJNI.OCRStudioSDKSession_ProcessImage(swigCPtr, this, OCRStudioSDKImage.getCPtr(image), image);
  }

  public void ProcessData(String data_str) {
    jniocrstudiosdkJNI.OCRStudioSDKSession_ProcessData(swigCPtr, this, data_str);
  }

  public OCRStudioSDKResult CurrentResult() {
    return new OCRStudioSDKResult(jniocrstudiosdkJNI.OCRStudioSDKSession_CurrentResult(swigCPtr, this), false);
  }

  public void Reset() {
    jniocrstudiosdkJNI.OCRStudioSDKSession_Reset(swigCPtr, this);
  }

  public void Suspend() {
    jniocrstudiosdkJNI.OCRStudioSDKSession_Suspend(swigCPtr, this);
  }

  public void Resume() {
    jniocrstudiosdkJNI.OCRStudioSDKSession_Resume(swigCPtr, this);
  }

}
