/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.ocrstudio.sdk;

public final class OCRStudioSDKPixelFormat {
  public final static OCRStudioSDKPixelFormat OCRSTUDIOSDK_PIXEL_FORMAT_G = new OCRStudioSDKPixelFormat("OCRSTUDIOSDK_PIXEL_FORMAT_G", jniocrstudiosdkJNI.OCRSTUDIOSDK_PIXEL_FORMAT_G_get());
  public final static OCRStudioSDKPixelFormat OCRSTUDIOSDK_PIXEL_FORMAT_GA = new OCRStudioSDKPixelFormat("OCRSTUDIOSDK_PIXEL_FORMAT_GA");
  public final static OCRStudioSDKPixelFormat OCRSTUDIOSDK_PIXEL_FORMAT_AG = new OCRStudioSDKPixelFormat("OCRSTUDIOSDK_PIXEL_FORMAT_AG");
  public final static OCRStudioSDKPixelFormat OCRSTUDIOSDK_PIXEL_FORMAT_RGB = new OCRStudioSDKPixelFormat("OCRSTUDIOSDK_PIXEL_FORMAT_RGB");
  public final static OCRStudioSDKPixelFormat OCRSTUDIOSDK_PIXEL_FORMAT_BGR = new OCRStudioSDKPixelFormat("OCRSTUDIOSDK_PIXEL_FORMAT_BGR");
  public final static OCRStudioSDKPixelFormat OCRSTUDIOSDK_PIXEL_FORMAT_BGRA = new OCRStudioSDKPixelFormat("OCRSTUDIOSDK_PIXEL_FORMAT_BGRA");
  public final static OCRStudioSDKPixelFormat OCRSTUDIOSDK_PIXEL_FORMAT_ARGB = new OCRStudioSDKPixelFormat("OCRSTUDIOSDK_PIXEL_FORMAT_ARGB");
  public final static OCRStudioSDKPixelFormat OCRSTUDIOSDK_PIXEL_FORMAT_RGBA = new OCRStudioSDKPixelFormat("OCRSTUDIOSDK_PIXEL_FORMAT_RGBA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OCRStudioSDKPixelFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OCRStudioSDKPixelFormat.class + " with value " + swigValue);
  }

  private OCRStudioSDKPixelFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OCRStudioSDKPixelFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OCRStudioSDKPixelFormat(String swigName, OCRStudioSDKPixelFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OCRStudioSDKPixelFormat[] swigValues = { OCRSTUDIOSDK_PIXEL_FORMAT_G, OCRSTUDIOSDK_PIXEL_FORMAT_GA, OCRSTUDIOSDK_PIXEL_FORMAT_AG, OCRSTUDIOSDK_PIXEL_FORMAT_RGB, OCRSTUDIOSDK_PIXEL_FORMAT_BGR, OCRSTUDIOSDK_PIXEL_FORMAT_BGRA, OCRSTUDIOSDK_PIXEL_FORMAT_ARGB, OCRSTUDIOSDK_PIXEL_FORMAT_RGBA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

