/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.ocrstudio.sdk;

public final class OCRStudioSDKYUVFormat {
  public final static OCRStudioSDKYUVFormat OCRSTUDIOSDK_YUV_FORMAT_NOT_SET = new OCRStudioSDKYUVFormat("OCRSTUDIOSDK_YUV_FORMAT_NOT_SET", jniocrstudiosdkJNI.OCRSTUDIOSDK_YUV_FORMAT_NOT_SET_get());
  public final static OCRStudioSDKYUVFormat OCRSTUDIOSDK_YUV_FORMAT_NV21 = new OCRStudioSDKYUVFormat("OCRSTUDIOSDK_YUV_FORMAT_NV21");
  public final static OCRStudioSDKYUVFormat OCRSTUDIOSDK_YUV_FORMAT_420_888 = new OCRStudioSDKYUVFormat("OCRSTUDIOSDK_YUV_FORMAT_420_888");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OCRStudioSDKYUVFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OCRStudioSDKYUVFormat.class + " with value " + swigValue);
  }

  private OCRStudioSDKYUVFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OCRStudioSDKYUVFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OCRStudioSDKYUVFormat(String swigName, OCRStudioSDKYUVFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OCRStudioSDKYUVFormat[] swigValues = { OCRSTUDIOSDK_YUV_FORMAT_NOT_SET, OCRSTUDIOSDK_YUV_FORMAT_NV21, OCRSTUDIOSDK_YUV_FORMAT_420_888 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

