/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.ocrstudio.sdk;

import ai.ocrstudio.sdk.*;

public class OCRStudioSDKItemIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OCRStudioSDKItemIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OCRStudioSDKItemIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(OCRStudioSDKItemIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniocrstudiosdkJNI.delete_OCRStudioSDKItemIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OCRStudioSDKItemIterator(OCRStudioSDKItemIterator copy) {
    this(jniocrstudiosdkJNI.new_OCRStudioSDKItemIterator(OCRStudioSDKItemIterator.getCPtr(copy), copy), true);
  }

  public boolean IsEqualTo(OCRStudioSDKItemIterator other) {
    return jniocrstudiosdkJNI.OCRStudioSDKItemIterator_IsEqualTo(swigCPtr, this, OCRStudioSDKItemIterator.getCPtr(other), other);
  }

  public OCRStudioSDKItemIterator Next() {
    return new OCRStudioSDKItemIterator(jniocrstudiosdkJNI.OCRStudioSDKItemIterator_Next(swigCPtr, this), true);
  }

  public void Step() {
    jniocrstudiosdkJNI.OCRStudioSDKItemIterator_Step(swigCPtr, this);
  }

  public String Key() {
    return jniocrstudiosdkJNI.OCRStudioSDKItemIterator_Key(swigCPtr, this);
  }

  public OCRStudioSDKItem Item() {
    return new OCRStudioSDKItem(jniocrstudiosdkJNI.OCRStudioSDKItemIterator_Item(swigCPtr, this), false);
  }

}
